### ISSUE TITLE
Hard to find you with the broken links

### ISSUE THREAD

**Issue by elitsa-bahovska** [msepcot/after_the_deadline#4]
The link in the readme is broken, and so is the one here: https://stackoverflow.com/questions/10252448/how-to-check-whether-a-sentence-is-correct-simple-grammar-check-in-python, from where I found you. you seem to have changed from .slp to .html, which makes finding you a bit difficult. Maybe a forwarding would help? Just thought you would want to know.

**Comment by msepcot** [comment]
Hi, I do not maintain the After the Deadline service, I just wrote this Ruby wrapper for it. Updated the link, thanks!
